version: "3.9"

services:
  maibao-field-shortcut:
    image: maibao-field-shortcut:latest
    container_name: maibao-field-shortcut
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: on-failure