FROM python:3.14-slim

RUN pip install --no-cache-dir -i https://mirrors.ustc.edu.cn/pypi/simple/ uv

WORKDIR /app

COPY pyproject.toml ./
COPY uv.lock ./

RUN uv sync --frozen -i https://mirrors.ustc.edu.cn/pypi/simple/

COPY main.py ./
COPY gunicorn.py ./
COPY services ./services
COPY API_PROTOCOL.md ./
COPY README.md ./

EXPOSE 5000

CMD ["./.venv/bin/gunicorn", "-c", "gunicorn.py", "main:app"]
